name: Process Scans in Dropbox
on: 
  workflow_dispatch:
jobs:
  docker-run:
    runs-on: ubuntu-latest
    steps:   
      - name: Checkout ðŸ›Žï¸
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Create env file
        run: |
          touch ./kook/.env
          echo APP_KEY=${{ secrets.APP_KEY }} >> ./kook/.env
          echo REFRESH_TOKEN=${{ secrets.REFRESH_TOKEN }} >> ./kook/.env
          cat ./kook/.env
      - name: Run Dockerfile
        run: |
          docker run \
          --env-file ./kook/.env \
          -v $(pwd)/kook/output/processed-index.json:/kook/kook/output/processed-index.json \
          -v $(pwd)/webapp:/kook/webapp \
          arbakker/kook:latest
      - uses: EndBug/add-and-commit@v8
        with:
          default_author: github_actions
      
  
