name: Process Scans in Dropbox
on: 
  workflow_dispatch:
  repository_dispatch:
    types: [dropbox-webhook]
jobs:
  docker-run:
    runs-on: ubuntu-latest
    steps:   
      - name: Checkout ðŸ›Žï¸
        uses: actions/checkout@v2
        with:
          persist-credentials: true
      - name: Turnstyle
        uses: softprops/turnstyle@v1
        with:
          abort-after-seconds: 60
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create env file
        run: |
          touch .env
          echo APP_KEY=${{ secrets.APP_KEY }} >> .env
          echo REFRESH_TOKEN=${{ secrets.REFRESH_TOKEN }} >> .env
      - name: Run Dockerfile
        run: |
          docker run \
          --env-file .env \
          -v $(pwd)/kook/output/processed-index.json:/kook/kook/output/processed-index.json \
          -v $(pwd)/webapp:/kook/webapp \
          arbakker/kook:latest
      - uses: EndBug/add-and-commit@v8
        with:
          default_author: github_actions
      
  
